version: '3.7'
services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
        depends_on:
            - redis 
            - db
        restart: on-failure
        environment:
            - FLASK_ENV=${FLASK_ENV}
            - FLASK_SECRET=${FLASK_SECRET}
            - PUBLIC_HOST=${PUBLIC_HOST}
            - MYSQL_HOST=db
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
    client:
        build: ./frontend
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
        depends_on:
            - backend
    redis:
        image: redis
        restart: on-failure
        volumes:
            - $REDIS_DATA:/data
    db:
        image: mariadb:latest
        volumes:
            - $MYSQL_DATA:/var/lib/mysql
        environment:
            #to connect : 
            #mysql --host=127.0.0.1 --port=3306 -u root -p
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - "3306:3306"
        restart: on-failure
        expose:
            - "3306"
