version: '2'
services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
        depends_on:
            - redis 
        restart: on-failure
    client:
        build: ./frontend
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
        depends_on: 
            - backend
    redis:
        image: redis