version: '2'
services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/backend
        depends_on:
            - redis 
        restart: on-failure
    client:
        build: ./frontend
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
        depends_on: 
            - backend
    redis:
        image: redis
    db:
        image: mariadb:latest
        volumes: 
            - ./db:/var/lib/mysql
        environment:
            #to connect : 
            #mysql --host=127.0.0.1 --port=3306 -u root -p
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        restart: on-failure
        expose: 
            - "3306"
